SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.OP:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'OP'
      defaultLifetime: 0
      backend: 'Filesystem'
      disable-container: true
      directory: 'assets/jsoncache'
