SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.OP:
    factory: OP\AssetCacheFactory
    constructor:
      namespace: 'OP'
      defaultLifetime: 360000000
      backend: 'Filesystem'
      disable-container: true
